// <auto-generated />
using System;
using ClassBusinessObject.AppDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassBusinessObject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250113184735_Migrations")]
    partial class Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassBusinessObject.Models.ClassSubject", b =>
                {
                    b.Property<int>("ClassSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassSubjectId"));

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ClassSubjectId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSubject");

                    b.HasData(
                        new
                        {
                            ClassSubjectId = 1,
                            ClassId = "SE1702",
                            CreatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterId = "SP25",
                            Status = true,
                            SubjectId = "PRM392"
                        },
                        new
                        {
                            ClassSubjectId = 2,
                            ClassId = "SE1702",
                            CreatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterId = "SP25",
                            Status = true,
                            SubjectId = "PRN231"
                        },
                        new
                        {
                            ClassSubjectId = 3,
                            ClassId = "SE1702",
                            CreatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterId = "SP25",
                            Status = true,
                            SubjectId = "MLN122"
                        });
                });

            modelBuilder.Entity("ClassBusinessObject.Models.Semester", b =>
                {
                    b.Property<string>("SemesterId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("SemesterId");

                    b.ToTable("Semester");

                    b.HasData(
                        new
                        {
                            SemesterId = "SP25",
                            EndDate = new DateOnly(2025, 3, 24),
                            SemesterName = "Spring2025",
                            StartDate = new DateOnly(2025, 1, 5),
                            Status = true
                        },
                        new
                        {
                            SemesterId = "SU25",
                            EndDate = new DateOnly(2025, 8, 11),
                            SemesterName = "Summer2025",
                            StartDate = new DateOnly(2025, 5, 8),
                            Status = true
                        },
                        new
                        {
                            SemesterId = "FA25",
                            EndDate = new DateOnly(2025, 11, 25),
                            SemesterName = "Fall2025",
                            StartDate = new DateOnly(2025, 9, 5),
                            Status = true
                        });
                });

            modelBuilder.Entity("ClassBusinessObject.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MajorId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("NumberOfSlot")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubjectId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            SubjectId = "PRM392",
                            CreatedAt = new DateTime(2025, 1, 14, 1, 47, 35, 214, DateTimeKind.Local).AddTicks(7991),
                            Description = "Description",
                            MajorId = "IT",
                            NumberOfSlot = 20,
                            Status = 1,
                            SubjectName = "Mobile Programing",
                            Term = 8,
                            UpdatedAt = new DateTime(2025, 1, 14, 1, 47, 35, 214, DateTimeKind.Local).AddTicks(8005)
                        },
                        new
                        {
                            SubjectId = "PRN231",
                            CreatedAt = new DateTime(2025, 1, 14, 1, 47, 35, 214, DateTimeKind.Local).AddTicks(8009),
                            Description = "Description",
                            MajorId = "IT",
                            NumberOfSlot = 20,
                            Status = 0,
                            SubjectName = "Building Cross-Platform Back-End Application With .NET",
                            Term = 7,
                            UpdatedAt = new DateTime(2025, 1, 14, 1, 47, 35, 214, DateTimeKind.Local).AddTicks(8009)
                        },
                        new
                        {
                            SubjectId = "MLN122",
                            CreatedAt = new DateTime(2025, 1, 14, 1, 47, 35, 214, DateTimeKind.Local).AddTicks(8011),
                            Description = "Description",
                            MajorId = "CA",
                            NumberOfSlot = 16,
                            Status = 2,
                            SubjectName = "Political economics of Marxism – Leninism",
                            Term = 6,
                            UpdatedAt = new DateTime(2025, 1, 14, 1, 47, 35, 214, DateTimeKind.Local).AddTicks(8012)
                        });
                });

            modelBuilder.Entity("ClassBusinessObject.Models.ClassSubject", b =>
                {
                    b.HasOne("ClassBusinessObject.Models.Semester", "Semester")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassBusinessObject.Models.Subject", "Subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ClassBusinessObject.Models.Semester", b =>
                {
                    b.Navigation("ClassSubjects");
                });

            modelBuilder.Entity("ClassBusinessObject.Models.Subject", b =>
                {
                    b.Navigation("ClassSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
