// <auto-generated />
using System;
using BusinessObject.AppDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250117013104_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR(8)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = "CE170288",
                            Address = "Phong Điền, Cần Thơ",
                            Name = "Nguyễn Quốc Hoàng",
                            Phone = "0333744591"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Major", b =>
                {
                    b.Property<string>("MajorId")
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR(4)");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("MajorId");

                    b.ToTable("Major");

                    b.HasData(
                        new
                        {
                            MajorId = "IB",
                            MajorName = "International Business"
                        },
                        new
                        {
                            MajorId = "IT",
                            MajorName = "Information Technology"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "AcademicStaff"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Chairperson"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Teacher"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR(8)");

                    b.Property<string>("MajorId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR(4)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("MajorId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = "IT0001",
                            MajorId = "IT",
                            Term = 2
                        },
                        new
                        {
                            StudentId = "IT0002",
                            MajorId = "IT",
                            Term = 3
                        },
                        new
                        {
                            StudentId = "IB0001",
                            MajorId = "IB",
                            Term = 4
                        },
                        new
                        {
                            StudentId = "IB0002",
                            MajorId = "IB",
                            Term = 5
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAvartar")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = "IT0001",
                            CreatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6022),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Email = "HoangNQIT0001@gmail.com",
                            FirstName = "Hoàng",
                            LastName = "Nguyễn",
                            MiddleName = "Quốc",
                            PasswordHash = "123",
                            PersonalEmail = "nqh@gmail.com",
                            PhoneNumber = "0333744591",
                            RoleId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6035),
                            UserAvartar = "123"
                        },
                        new
                        {
                            UserId = "IT0002",
                            CreatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6038),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Email = "ThinhNTIT0002@gmail.com",
                            FirstName = "Thịnh",
                            LastName = "Nguyễn",
                            MiddleName = "Tuấn",
                            PasswordHash = "123",
                            PersonalEmail = "nqh@gmail.com",
                            PhoneNumber = "0333744591",
                            RoleId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6039),
                            UserAvartar = "123"
                        },
                        new
                        {
                            UserId = "IB0001",
                            CreatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6041),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Email = "ThangNTIB0001@gmail.com",
                            FirstName = "Thắng",
                            LastName = "Nguyễn",
                            MiddleName = "Toàn",
                            PasswordHash = "123",
                            PersonalEmail = "nqh@gmail.com",
                            PhoneNumber = "0333744591",
                            RoleId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6042),
                            UserAvartar = "123"
                        },
                        new
                        {
                            UserId = "IB0002",
                            CreatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6044),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Email = "AnLDIB0002@gmail.com",
                            FirstName = "Ân",
                            LastName = "Lê",
                            MiddleName = "Đức",
                            PasswordHash = "123",
                            PersonalEmail = "nqh@gmail.com",
                            PhoneNumber = "0333744591",
                            RoleId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 1, 17, 8, 31, 2, 319, DateTimeKind.Local).AddTicks(6044),
                            UserAvartar = "123"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.Student", b =>
                {
                    b.HasOne("BusinessObject.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("BusinessObject.Models.Student", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.HasOne("BusinessObject.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.Models.Major", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("BusinessObject.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
