// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerBusinessObject.AppDBContext;

#nullable disable

namespace SchedulerBusinessObject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241202025700_Init_SchedulerService")]
    partial class Init_SchedulerService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR(6)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("OnlineURL")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isOnline")
                        .HasColumnType("BIT");

                    b.HasKey("RoomId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = "G304",
                            CreateAt = new DateTime(2024, 12, 2, 9, 57, 0, 221, DateTimeKind.Local).AddTicks(1425),
                            Location = "Grammar Room 304",
                            Status = 1,
                            UpdateAt = new DateTime(2024, 12, 2, 9, 57, 0, 221, DateTimeKind.Local).AddTicks(1435),
                            isOnline = false
                        },
                        new
                        {
                            RoomId = "R.ON",
                            CreateAt = new DateTime(2024, 12, 2, 9, 57, 0, 221, DateTimeKind.Local).AddTicks(1437),
                            Location = "Online",
                            OnlineURL = "https://meet.google.com/koi-kghw-tsy",
                            Status = 1,
                            UpdateAt = new DateTime(2024, 12, 2, 9, 57, 0, 221, DateTimeKind.Local).AddTicks(1437),
                            isOnline = true
                        });
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("INT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("DATE");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR(6)");

                    b.Property<int>("SlotId")
                        .HasColumnType("INT");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR(8)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SlotId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.TimeSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TIME(7)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TIME(7)");

                    b.HasKey("SlotId");

                    b.ToTable("TimeSlot");

                    b.HasData(
                        new
                        {
                            SlotId = 1,
                            EndTime = new TimeOnly(9, 15, 0),
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            SlotId = 2,
                            EndTime = new TimeOnly(11, 45, 0),
                            StartTime = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            SlotId = 3,
                            EndTime = new TimeOnly(15, 15, 0),
                            StartTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SlotId = 4,
                            EndTime = new TimeOnly(17, 45, 0),
                            StartTime = new TimeOnly(15, 30, 0)
                        },
                        new
                        {
                            SlotId = 5,
                            EndTime = new TimeOnly(20, 15, 0),
                            StartTime = new TimeOnly(18, 0, 0)
                        });
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Schedule", b =>
                {
                    b.HasOne("SchedulerBusinessObject.SchedulerModels.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulerBusinessObject.SchedulerModels.TimeSlot", "Slot")
                        .WithMany("Schedules")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Room", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.TimeSlot", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
