// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerBusinessObject.AppDBContext;

#nullable disable

namespace SchedulerBusinessObject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250226055647_AddRequest")]
    partial class AddRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.ExamSchedule", b =>
                {
                    b.Property<int>("ExamScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("DATE");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TIME(7)");

                    b.Property<string>("MajorId")
                        .HasColumnType("NVARCHAR(4)");

                    b.Property<string>("RoomId")
                        .HasColumnType("NVARCHAR(6)");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(4)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TIME(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("TeacherId")
                        .HasColumnType("NVARCHAR(8)");

                    b.HasKey("ExamScheduleId");

                    b.ToTable("ExamSchedule");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.RequestSchedule", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AlternateTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsChangeTeacher")
                        .HasColumnType("bit");

                    b.Property<string>("RequestTeacher")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INT");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("RequestSchedule");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("NVARCHAR(6)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = "G201",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8664),
                            Location = "Grammar Room 201",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8677)
                        },
                        new
                        {
                            RoomId = "G202",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8680),
                            Location = "Grammar Room 202",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8681)
                        },
                        new
                        {
                            RoomId = "G203",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8683),
                            Location = "Grammar Room 203",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8684)
                        },
                        new
                        {
                            RoomId = "G204",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8686),
                            Location = "Grammar Room 204",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8687)
                        },
                        new
                        {
                            RoomId = "G205",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8688),
                            Location = "Grammar Room 205",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8689)
                        },
                        new
                        {
                            RoomId = "G301",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8691),
                            Location = "Grammar Room 301",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8692)
                        },
                        new
                        {
                            RoomId = "G302",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8693),
                            Location = "Grammar Room 302",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8694)
                        },
                        new
                        {
                            RoomId = "G303",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8696),
                            Location = "Grammar Room 303",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8697)
                        },
                        new
                        {
                            RoomId = "G304",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8698),
                            Location = "Grammar Room 304",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8699)
                        },
                        new
                        {
                            RoomId = "G305",
                            CreateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8701),
                            Location = "Grammar Room 305",
                            Status = 1,
                            UpdateAt = new DateTime(2025, 2, 26, 12, 56, 47, 680, DateTimeKind.Local).AddTicks(8702)
                        });
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("INT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("DATE");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(6)");

                    b.Property<int>("SlotId")
                        .HasColumnType("INT");

                    b.Property<int>("SlotNoInSubject")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR(8)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SlotId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.StudentInExamSchedule", b =>
                {
                    b.Property<int>("StudentExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentExamId"));

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("INT");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(8)");

                    b.HasKey("StudentExamId");

                    b.HasIndex("ExamScheduleId");

                    b.ToTable("StudentInExamSchedule");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.TimeSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TIME(0)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.HasKey("SlotId");

                    b.ToTable("TimeSlot");

                    b.HasData(
                        new
                        {
                            SlotId = 1,
                            EndTime = new TimeOnly(9, 15, 0),
                            StartTime = new TimeOnly(7, 0, 0),
                            Status = 1
                        },
                        new
                        {
                            SlotId = 2,
                            EndTime = new TimeOnly(11, 45, 0),
                            StartTime = new TimeOnly(9, 30, 0),
                            Status = 1
                        },
                        new
                        {
                            SlotId = 3,
                            EndTime = new TimeOnly(15, 15, 0),
                            StartTime = new TimeOnly(13, 0, 0),
                            Status = 1
                        },
                        new
                        {
                            SlotId = 4,
                            EndTime = new TimeOnly(17, 45, 0),
                            StartTime = new TimeOnly(15, 30, 0),
                            Status = 1
                        },
                        new
                        {
                            SlotId = 5,
                            EndTime = new TimeOnly(20, 15, 0),
                            StartTime = new TimeOnly(18, 0, 0),
                            Status = 1
                        });
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.RequestSchedule", b =>
                {
                    b.HasOne("SchedulerBusinessObject.SchedulerModels.Schedule", "Schedule")
                        .WithOne("RequestSchedule")
                        .HasForeignKey("SchedulerBusinessObject.SchedulerModels.RequestSchedule", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Schedule", b =>
                {
                    b.HasOne("SchedulerBusinessObject.SchedulerModels.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulerBusinessObject.SchedulerModels.TimeSlot", "Slot")
                        .WithMany("Schedules")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.StudentInExamSchedule", b =>
                {
                    b.HasOne("SchedulerBusinessObject.SchedulerModels.ExamSchedule", null)
                        .WithMany("StudentInExamSchedules")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.ExamSchedule", b =>
                {
                    b.Navigation("StudentInExamSchedules");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Room", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.Schedule", b =>
                {
                    b.Navigation("RequestSchedule");
                });

            modelBuilder.Entity("SchedulerBusinessObject.SchedulerModels.TimeSlot", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
